# Site settings
title: "Wealth Route Finder"
description: "Your guide to building wealth through smart financial decisions"
baseurl: ""
url: "https://wealthroutefinder.com"

# Build settings
markdown: kramdown
permalink: /:title/

# Google Analytics
google_analytics: G-LSSE13TM0D

# Amazon Affiliate
amazon_affiliate_id: ivanykallc-20

# Collections
collections:
  posts:
    output: true
    permalink: /:title/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
